apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - http:
        paths:
          - path: /auth/?(.*)
            backend:
              serviceName: auth-srv
              servicePort: 3000
          - path: /activity-backlog/?(.*)
            backend:
              serviceName: activity-backlog-srv
              servicePort: 3000
          - path: /activity-listener/?(.*)
            backend:
              serviceName: activity-listener-srv
              servicePort: 3000
          - path: /event-bus/?(.*)
            backend:
              serviceName: event-bus-srv
              servicePort: 3000
          - path: /activities/?(.*)
            backend:
              serviceName: activities-srv
              servicePort: 3000
          - path: /?(.*)
            backend:
              serviceName: client-srv
              servicePort: 3000
